nome = str(input('Digite seu nome completo: ')).strip()
print('O nome em maiúsculo fica: {}' .format(nome.upper()))
print('O nome em minúsculo fica: {}' .format(nome.lower()))
##nomecompleto = len(nome.strip())
print('O nome tem {} letras' .format(len(nome)-nome.count(' ')))
print('O primeiro nome tem {}' .format(nome.find(' ')))
separado = nome.split()
print('Seu primeiro nome é {} e tem {} letras' .format(separado[0], len(separado[0])))